# Site settings
title: David Plehn's Blog
SEOTitle: David Plehn's Blog
header-img: /img/Snowy_Mountian_Header.jpg
email: davidplehn07@gmail.com
description: "Never stop climbing and you'll reach the summit."
keyword: "David Plehn, David Plehn Blog, Plehndm, College, UCI"
url: "http://Plehndm.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Plehndm/Plehndm.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hardwork always pays off!"
sidebar-avatar: /img/profile_photo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    Plehndm
instagram_username: dplehn_314
linkedin_username:  david-plehn




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 统计

# Analytics settings
# Google Analytics
ga_track_id: 'G-8YDS9ZPXM8'             # Format: G-xxxxxxxxxx
ga_domain: auto                         # default is auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

